import os
import re
import time

from ..state import VibeDeployState
from ..tools.digitalocean import build_app_spec, deploy_to_digitalocean, wait_for_deployment
from ..tools.github import create_github_repo


async def deployer(state: VibeDeployState) -> dict:
    frontend_code = state.get("frontend_code", {}) or {}
    backend_code = state.get("backend_code", {}) or {}
    idea = state.get("idea", {}) or {}

    app_name = _build_repo_name(idea)
    description = idea.get("tagline") or idea.get("problem") or "Generated by vibeDeploy"
    all_files = _merge_files(frontend_code, backend_code)
    github_org = os.getenv("GITHUB_ORG")

    github_result = await create_github_repo(
        name=app_name,
        files=all_files,
        description=description,
        org=github_org or None,
    )

    github_repo_url = github_result.get("url", "")
    github_clone_url = github_result.get("clone_url", "")

    if github_result.get("status") == "error" or not github_clone_url:
        error_message = github_result.get("error", "GitHub repository creation failed")
        return {
            "deploy_result": {
                "app_id": "",
                "live_url": "",
                "github_repo": github_repo_url,
                "status": f"github_error: {error_message}",
            },
            "phase": "deployed",
        }

    app_spec = build_app_spec(app_name, github_clone_url)
    deploy_result = await deploy_to_digitalocean(github_clone_url, app_spec)

    if deploy_result.get("status") == "error":
        error_message = deploy_result.get("error", "DigitalOcean deployment failed")
        return {
            "deploy_result": {
                "app_id": deploy_result.get("app_id", ""),
                "live_url": "",
                "github_repo": github_repo_url,
                "status": f"deployment_error: {error_message}",
            },
            "phase": "deployed",
        }

    app_id = deploy_result.get("app_id", "")
    live_url = await wait_for_deployment(app_id) if app_id else ""

    status = "deployed" if live_url else "deployment_started"
    return {
        "deploy_result": {
            "app_id": app_id,
            "live_url": live_url,
            "github_repo": github_repo_url,
            "status": status,
        },
        "phase": "deployed",
    }


def _merge_files(frontend_code: dict, backend_code: dict) -> dict[str, str]:
    merged: dict[str, str] = {}

    for path, content in backend_code.items():
        if isinstance(path, str) and isinstance(content, str):
            merged[path] = content

    for path, content in frontend_code.items():
        if not isinstance(path, str) or not isinstance(content, str):
            continue

        normalized_path = path if path.startswith("web/") else f"web/{path}"
        merged[normalized_path] = content

    return merged


def _build_repo_name(idea: dict) -> str:
    base_name = idea.get("name") or idea.get("tagline") or "vibedeploy-app"
    slug = re.sub(r"[^a-zA-Z0-9\s-]", "", str(base_name)).strip().lower()
    slug = re.sub(r"[\s_]+", "-", slug)
    slug = re.sub(r"-+", "-", slug)
    slug = slug[:45].strip("-") or "vibedeploy-app"

    suffix = str(int(time.time()))[-6:]
    return f"{slug}-{suffix}"
