import asyncio
import json
import os
import re
import socket
import time
from pathlib import Path
from urllib import error, request

from ..state import VibeDeployState
from ..tools.digitalocean import build_app_spec, deploy_to_digitalocean, wait_for_deployment
from ..tools.github import create_github_repo, get_ci_failure_logs, push_files, wait_for_ci


async def deployer(state: VibeDeployState) -> dict:
    frontend_code = state.get("frontend_code", {}) or {}
    backend_code = state.get("backend_code", {}) or {}
    idea = state.get("idea", {}) or {}

    app_name = _build_repo_name(idea)
    description = idea.get("tagline") or idea.get("problem") or "Generated by vibeDeploy"
    all_files = _merge_files(frontend_code, backend_code)
    has_frontend = any(k.startswith("web/") for k in all_files)
    all_files.update(
        {
            "README.md": _generate_readme(idea, state.get("scoring") or {}, backend_code),
            ".github/workflows/ci.yml": _generate_ci_yml(has_frontend=has_frontend),
            ".env.example": _generate_env_example(),
        }
    )
    github_org = os.getenv("GITHUB_ORG")

    github_result = await create_github_repo(
        name=app_name,
        files=all_files,
        description=description,
        org=github_org or None,
    )

    github_repo_url = github_result.get("url", "")
    github_clone_url = github_result.get("clone_url", "")
    github_full_name = github_result.get("full_name", "")

    if github_result.get("status") == "error" or not github_clone_url:
        error_message = github_result.get("error", "GitHub repository creation failed")
        return {
            "deploy_result": {
                "app_id": "",
                "live_url": "",
                "github_repo": github_repo_url,
                "status": f"github_error: {error_message}",
            },
            "phase": "deployed",
        }

    supporting_files = {
        "README.md": _generate_readme(idea, state.get("scoring") or {}, backend_code),
        ".github/workflows/ci.yml": _generate_ci_yml(has_frontend=has_frontend),
        ".env.example": _generate_env_example(),
    }
    commit_sha = ""
    if github_full_name:
        push_result = await push_files(
            {"full_name": github_full_name},
            supporting_files,
            commit_message="Add project docs, CI workflow, and env example",
        )
        commit_sha = push_result.get("commit_sha", "")
        _set_repo_metadata(
            github_full_name,
            topics=["ai", "fastapi", "nextjs", "digitalocean", "vibedeploy", "hackathon", "llm"],
            homepage="https://github.com/Two-Weeks-Team/vibeDeploy",
        )

    ci_result = {"status": "skipped"}
    repair_attempts = 0
    if github_full_name and commit_sha:
        ci_result, all_files, repair_attempts = await _ci_repair_loop(
            github_full_name, commit_sha, all_files, max_retries=3
        )

    ci_meta = {
        "ci_status": ci_result.get("status", "skipped"),
        "ci_url": ci_result.get("url", ""),
        "ci_repair_attempts": repair_attempts,
    }

    do_token = os.getenv("DIGITALOCEAN_API_TOKEN")
    if not do_token:
        result = await _local_fallback_deploy(app_name, all_files, github_repo_url, "do_token_missing")
        result["deploy_result"].update(ci_meta)
        return result

    app_spec = build_app_spec(app_name, github_clone_url)
    deploy_result = await deploy_to_digitalocean(github_clone_url, app_spec)

    if deploy_result.get("status") == "error":
        result = await _local_fallback_deploy(
            app_name,
            all_files,
            github_repo_url,
            f"do_deploy_failed: {deploy_result.get('error', 'DigitalOcean deployment failed')}",
            app_id=deploy_result.get("app_id", ""),
        )
        result["deploy_result"].update(ci_meta)
        return result

    app_id = deploy_result.get("app_id", "")
    live_url = await wait_for_deployment(app_id) if app_id else ""

    status = "deployed" if live_url else "deployment_started"
    return {
        "deploy_result": {
            "app_id": app_id,
            "live_url": live_url,
            "github_repo": github_repo_url,
            "status": status,
            **ci_meta,
        },
        "phase": "deployed",
    }


_CI_REPAIR_PROMPT = """You are a CI repair engineer. Fix the failing code so CI passes.

Rules:
- Only fix files that caused the CI failure. Do NOT rewrite working files.
- For Python: fix imports, dependency names in requirements.txt, syntax errors.
- For Node/TypeScript: fix package.json deps, type errors, build errors.
- Return ONLY the corrected files as JSON: { "files": { "path": "content" } }
- If a file doesn't need changes, do NOT include it.
- Keep all existing functionality — minimal fixes only.
"""


async def _ci_repair_loop(
    full_name: str,
    commit_sha: str,
    files: dict[str, str],
    max_retries: int = 3,
) -> tuple[dict, dict[str, str], int]:
    for attempt in range(1, max_retries + 1):
        ci_result = await wait_for_ci(full_name, commit_sha, timeout=180)

        if ci_result.get("status") == "passed":
            return ci_result, files, attempt - 1

        if ci_result.get("status") in ("timeout", "skipped"):
            return ci_result, files, attempt - 1

        error_logs = await get_ci_failure_logs(full_name, commit_sha)
        if not error_logs:
            return ci_result, files, attempt

        fixed_files = await _repair_code_from_errors(files, error_logs)
        if fixed_files == files:
            return ci_result, files, attempt

        files = fixed_files
        push_result = await push_files(
            {"full_name": full_name},
            files,
            commit_message=f"fix: CI repair attempt {attempt}",
        )
        commit_sha = push_result.get("commit_sha", "")
        if not commit_sha:
            return ci_result, files, attempt

    final_ci = await wait_for_ci(full_name, commit_sha, timeout=180)
    return final_ci, files, max_retries


async def _repair_code_from_errors(files: dict[str, str], error_logs: str) -> dict[str, str]:
    from ..llm import MODEL_CONFIG, content_to_str, get_llm

    llm = get_llm(model=MODEL_CONFIG["ci_repair"], temperature=0.1, max_tokens=8000)

    file_listing = "\n\n".join(
        f"=== {path} ===\n{content}" for path, content in sorted(files.items()) if isinstance(content, str)
    )

    try:
        response = await llm.ainvoke(
            [
                {"role": "system", "content": _CI_REPAIR_PROMPT},
                {
                    "role": "user",
                    "content": f"CI ERROR LOG:\n{error_logs[:4000]}\n\nCURRENT FILES:\n{file_listing}",
                },
            ]
        )
    except Exception:
        return files

    raw = content_to_str(response.content).strip()
    parsed = _parse_repair_json(raw)
    if not parsed:
        return files

    result = dict(files)
    for path, content in parsed.items():
        if isinstance(path, str) and isinstance(content, str):
            result[path] = content
    return result


def _parse_repair_json(raw: str) -> dict[str, str] | None:
    if raw.startswith("```"):
        raw = re.sub(r"^```(?:json)?\n?", "", raw)
        raw = re.sub(r"\n?```$", "", raw)

    try:
        data = json.loads(raw)
    except json.JSONDecodeError:
        match = re.search(r"\{[\s\S]*\}", raw)
        if not match:
            return None
        try:
            data = json.loads(match.group())
        except json.JSONDecodeError:
            return None

    if isinstance(data, dict) and "files" in data:
        return data["files"] if isinstance(data["files"], dict) else None
    return data if isinstance(data, dict) else None


async def _local_fallback_deploy(
    app_name: str,
    files: dict[str, str],
    github_repo_url: str,
    reason: str,
    app_id: str = "",
) -> dict:
    base_dir = Path("/tmp/vibedeploy-apps") / _sanitize_app_name(app_name)
    _write_local_files(base_dir, files)

    backend_port = _find_free_port(start_port=9100)
    frontend_port = _find_free_port(start_port=backend_port + 1)

    requirements_path = base_dir / "requirements.txt"
    if requirements_path.exists():
        await _spawn_background_process(["pip", "install", "-r", "requirements.txt"], base_dir)

    web_dir = base_dir / "web"
    package_json_path = web_dir / "package.json"
    if package_json_path.exists():
        await _spawn_background_process(["npm", "install"], web_dir)

    backend_main = base_dir / "main.py"
    if backend_main.exists():
        await _spawn_background_process(
            ["uvicorn", "main:app", "--host", "127.0.0.1", "--port", str(backend_port)],
            base_dir,
        )

    if package_json_path.exists():
        await _spawn_background_process(["npm", "run", "dev", "--", "--port", str(frontend_port)], web_dir)

    local_backend_url = f"http://127.0.0.1:{backend_port}"
    local_frontend_url = f"http://127.0.0.1:{frontend_port}"

    return {
        "deploy_result": {
            "app_id": app_id,
            "live_url": "",
            "github_repo": github_repo_url,
            "status": "local_running",
            "local_reason": reason,
            "local_url": local_frontend_url,
            "local_backend_url": local_backend_url,
            "local_frontend_url": local_frontend_url,
        },
        "phase": "deployed",
    }


def _write_local_files(base_dir: Path, files: dict[str, str]) -> None:
    base_dir.mkdir(parents=True, exist_ok=True)
    for rel_path, content in files.items():
        if not isinstance(rel_path, str) or not isinstance(content, str):
            continue
        target_path = (base_dir / rel_path).resolve()
        if base_dir.resolve() not in target_path.parents and target_path != base_dir.resolve():
            continue
        target_path.parent.mkdir(parents=True, exist_ok=True)
        target_path.write_text(content, encoding="utf-8")


async def _spawn_background_process(command: list[str], cwd: Path) -> None:
    await asyncio.create_subprocess_exec(
        *command,
        cwd=str(cwd),
        stdout=asyncio.subprocess.DEVNULL,
        stderr=asyncio.subprocess.DEVNULL,
        start_new_session=True,
    )


def _find_free_port(start_port: int) -> int:
    for port in range(start_port, start_port + 200):
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
            sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
            if sock.connect_ex(("127.0.0.1", port)) != 0:
                return port
    return start_port


def _sanitize_app_name(app_name: str) -> str:
    return re.sub(r"[^a-zA-Z0-9_-]", "-", app_name).strip("-") or "vibedeploy-app"


def _set_repo_metadata(full_name: str, topics: list[str], homepage: str) -> None:
    token = os.getenv("GITHUB_TOKEN")
    if not token or not full_name:
        return

    _github_api_request(
        method="PATCH",
        path=f"/repos/{full_name}",
        token=token,
        payload={"homepage": homepage},
    )
    _github_api_request(
        method="PUT",
        path=f"/repos/{full_name}/topics",
        token=token,
        payload={"names": topics},
    )


def _github_api_request(method: str, path: str, token: str, payload: dict) -> None:
    data = json.dumps(payload).encode("utf-8")
    req = request.Request(
        url=f"https://api.github.com{path}",
        data=data,
        method=method,
        headers={
            "Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
            "Content-Type": "application/json",
        },
    )
    try:
        with request.urlopen(req, timeout=15):
            pass
    except (error.HTTPError, error.URLError):
        return


def _generate_readme(idea: dict, scoring: dict, backend_code: dict) -> str:
    app_name = str(idea.get("name") or "vibeDeploy App")
    tagline = str(idea.get("tagline") or idea.get("problem") or "An application generated by vibeDeploy.")
    problem = str(idea.get("problem") or "No problem statement provided.")
    features = idea.get("features") or []
    if not isinstance(features, list):
        features = []

    tech_stack = idea.get("tech_stack") or {}
    if isinstance(tech_stack, list):
        tech_entries = [str(item) for item in tech_stack]
    elif isinstance(tech_stack, dict):
        tech_entries = [f"{k}: {v}" for k, v in tech_stack.items()]
    else:
        tech_entries = ["Backend: FastAPI", "Frontend: Next.js"]

    endpoints = _extract_api_endpoints(backend_code)
    endpoint_rows = "\n".join([f"| `{m}` | `{p}` |" for m, p in endpoints])
    if not endpoint_rows:
        endpoint_rows = "| `GET` | `/health` |"

    feature_lines = (
        "\n".join([f"- {str(item)}" for item in features[:8]]) or "- Core functionality generated from your idea"
    )
    tech_rows = "\n".join(
        [
            f"| {entry.split(':', 1)[0].strip()} | {entry.split(':', 1)[1].strip() if ':' in entry else entry} |"
            for entry in tech_entries
        ]
    )

    vibe_score = scoring.get("final_score")
    vibe_footer = f"Vibe Score: **{vibe_score}**" if vibe_score is not None else "Vibe Score: not available"

    github_org = os.getenv("GITHUB_ORG", "Two-Weeks-Team")

    return f"""# {app_name}

<p align="center">
  <img src="https://img.shields.io/badge/AI-Powered-blueviolet?style=for-the-badge" alt="AI Powered"/>
  <img src="https://img.shields.io/badge/Python-3.14-3776AB?style=for-the-badge&logo=python&logoColor=white" alt="Python"/>
  <img src="https://img.shields.io/badge/FastAPI-0.135-009688?style=for-the-badge&logo=fastapi&logoColor=white" alt="FastAPI"/>
  <img src="https://img.shields.io/badge/Next.js-16-black?style=for-the-badge&logo=next.js" alt="Next.js"/>
  <img src="https://img.shields.io/badge/license-MIT-green?style=for-the-badge" alt="MIT"/>
</p>

> {tagline}

---

## Overview

{problem}

## Key Features

{feature_lines}

## Architecture

```
+------------------+        +---------------------+        +------------------+
|                  |  HTTP   |                     |  HTTP  |                  |
|   Next.js 16     +------->+   FastAPI Backend    +------->+  DO Inference    |
|   Frontend       |  REST   |   Python 3.14       |  AI    |  (gpt-5-mini)   |
|   (port 3000)    +<-------+   (port 8000)        +<------+                  |
|                  |  JSON   |                     |  JSON  |                  |
+------------------+        +----------+----------+        +------------------+
                                       |
                              +--------v--------+
                              |   PostgreSQL     |
                              |   (psycopg 3.3)  |
                              +-----------------+
```

## API Endpoints

| Method | Path |
|--------|------|
{endpoint_rows}

## Tech Stack

| Layer | Technology | Version |
|-------|-----------|---------|
| Runtime | Python | 3.14+ |
| Backend | FastAPI + uvicorn | 0.135.1 |
| Frontend | Next.js + React | 16.1.6 / 19.2.4 |
| Database | PostgreSQL + psycopg | 3.3.3 |
| AI | DO Serverless Inference | gpt-5-mini |
| Styling | Tailwind CSS | 4.2.1 |
{tech_rows}

## Quick Start

### Prerequisites

- Python 3.14+
- Node.js 24+

### Run Locally

```bash
# Backend
python -m venv .venv && source .venv/bin/activate
pip install -r requirements.txt
cp .env.example .env   # fill in your keys
uvicorn main:app --reload --port 8000

# Frontend (new terminal)
cd web
npm install
npm run dev
```

## Environment Variables

Copy `.env.example` to `.env` and fill in values:

- `API_BASE_URL`
- `ENVIRONMENT`
- `LOG_LEVEL`

## Deploying to DigitalOcean

This app is designed for [DigitalOcean App Platform](https://www.digitalocean.com/products/app-platform):

```yaml
name: {app_name.lower().replace(" ", "-")}
services:
  - name: api
    github:
      repo: {github_org}/{app_name.lower().replace(" ", "-")}
      branch: master
    build_command: pip install -r requirements.txt
    run_command: uvicorn main:app --host 0.0.0.0 --port $PORT
    http_port: 8080
    instance_size_slug: apps-s-1vcpu-0.5gb
    envs:
      - key: DIGITALOCEAN_INFERENCE_KEY
        scope: RUN_TIME
        type: SECRET
static_sites:
  - name: web
    github:
      repo: {github_org}/{app_name.lower().replace(" ", "-")}
      branch: master
    source_dir: web
    build_command: npm install && npm run build
    output_dir: web/.next
```

---

<p align="center">
  Generated by <a href="https://github.com/{github_org}/vibeDeploy"><strong>vibeDeploy</strong></a> | {vibe_footer}
</p>
"""


def _extract_api_endpoints(backend_code: dict) -> list[tuple[str, str]]:
    endpoints: list[tuple[str, str]] = []
    route_pattern = re.compile(r"@app\.(get|post|put|patch|delete)\(\s*['\"]([^'\"]+)['\"]")

    for content in backend_code.values():
        if not isinstance(content, str):
            continue
        for method, path in route_pattern.findall(content):
            endpoint = (method.upper(), path)
            if endpoint not in endpoints:
                endpoints.append(endpoint)

    return endpoints


def _generate_ci_yml(has_frontend: bool = False) -> str:
    backend_job = """  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          allow-prereleases: true
      - name: Install backend dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "No requirements.txt found, skipping"
          fi
      - name: Backend smoke test
        run: python -c "import ast; [ast.parse(open(f).read()) for f in __import__('glob').glob('*.py')]"
"""

    frontend_job = """
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install frontend dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          elif [ -f package.json ]; then
            npm install
          else
            echo "No package.json found, skipping"
            exit 0
          fi
      - name: Build frontend
        run: |
          if [ -f package.json ]; then
            npm run build
          fi
"""

    yml = """name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:

jobs:
"""
    yml += backend_job
    if has_frontend:
        yml += frontend_job
    return yml


def _generate_env_example() -> str:
    return """DIGITALOCEAN_INFERENCE_KEY=your-do-inference-key
DO_INFERENCE_MODEL=gpt-5-mini
DATABASE_URL=postgresql://user:pass@localhost:5432/myapp
NEXT_PUBLIC_API_BASE_URL=http://127.0.0.1:8000
"""


def _merge_files(frontend_code: dict, backend_code: dict) -> dict[str, str]:
    merged: dict[str, str] = {}

    for path, content in backend_code.items():
        if isinstance(path, str) and isinstance(content, str):
            merged[path] = content

    for path, content in frontend_code.items():
        if not isinstance(path, str) or not isinstance(content, str):
            continue

        normalized_path = path if path.startswith("web/") else f"web/{path}"
        merged[normalized_path] = content

    return merged


def _build_repo_name(idea: dict) -> str:
    base_name = idea.get("name") or idea.get("tagline") or "vibedeploy-app"
    slug = re.sub(r"[^a-zA-Z0-9\s-]", "", str(base_name)).strip().lower()
    slug = re.sub(r"[\s_]+", "-", slug)
    slug = re.sub(r"-+", "-", slug)
    slug = slug[:45].strip("-") or "vibedeploy-app"

    suffix = str(int(time.time()))[-6:]
    return f"{slug}-{suffix}"
