FRONTEND_TEMPLATE = """// Frontend template stub
export default function App() {
  return null;
}
"""

BACKEND_TEMPLATE = """# Backend template stub
def main() -> None:
    return None
"""

README_TEMPLATE = """# Generated App

This repository was generated by vibeDeploy.
"""
